### ISSUE TITLE
 No such file or directory: './options.json'

### ISSUE THREAD

**Issue by nimafo** [valentin-deschaintre/Single-Image-SVBRDF-Capture-rendering-loss#7]
Hi,
Thank you for this interesting research, I want to reproduce the results by running the shell script you provided, I see the following issue though, how can I resolve that? I am using a recent version of TensorFlow on Ubuntu on WSL on Windows 11 and I am NOT using CUDA for testing.

> Traceback (most recent call last):
>   File "Single-Image-SVBRDF-Capture-rendering-loss/material_net.py", line 1162, in <module>
>     main()
>   File "Single-Image-SVBRDF-Capture-rendering-loss/material_net.py", line 861, in main
>     with open(os.path.join(a.checkpoint, "options.json")) as f:
> FileNotFoundError: [Errno 2] No such file or directory: './options.json'

Thanks in advance,
Nima

**Comment by valentin-deschaintre** [comment]
Hi,

I believe this file should be part of the network weights for which you can find a link in the repo readme. Let me know if that doesn't solve your issue.

Valentin
